#qc_diagnostics.py
"""
QC Diagnostics for Copper-Driven Resistance RL Study
Author: Hayden Hedman
Date: 2025-12-10

This script performs biological sanity-checks on the raw simulation output
generated by run_experiments.py.

Outputs:
- Basic descriptive stats for copper & MIC trajectories
- Validation of expected biological behaviors:
    1. MIC upward drift under sustained copper exposure
    2. MIC partial reversal under low copper exposure
    3. Growth inhibition inversely related to total MIC
    4. No runaway divergence exceeding Li et al. 2021 ranges

Results saved under: /src/outputs/summary_tables/qc/
"""

import pandas as pd
import numpy as np
from pathlib import Path

# -----------------------------------------------------------
# Paths
# -----------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parents[1]
RAW_DIR = PROJECT_ROOT / "outputs" / "raw_csv"
QC_DIR = PROJECT_ROOT / "outputs" / "summary_tables" / "qc"
QC_DIR.mkdir(parents=True, exist_ok=True)

AGENT_FILES = {
    "Random": RAW_DIR / "random_policy_results.csv",
    "Rule-Based": RAW_DIR / "rule_based_results.csv",
    "Q-Learner": RAW_DIR / "q_learner_results.csv",
}

# -----------------------------------------------------------
# Helper: compute slope of MIC vs cycle
# -----------------------------------------------------------
def compute_mic_slope(df, mic_col):
    """Returns slope of MIC vs cycle using OLS."""
    cycles = df["cycle"].values
    mic = df[mic_col].values
    if len(cycles) < 5:
        return np.nan
    slope = np.polyfit(cycles, mic, 1)[0]
    return slope

# -----------------------------------------------------------
# Helper: check for biological signature behaviors
# -----------------------------------------------------------
def biological_signatures(df):
    """
    Returns dict of biological QC checks:
    - upward MIC drift under sustained copper
    - downward MIC drift when copper low
    - correlation between MIC burden and growth inhibition
    """
    results = {}
    
    # 1. correlation: MIC sum vs growth inhibition (should be negative)
    df["MIC_total"] = df["MIC_chloro"] + df["MIC_polyB"]
    corr = df["MIC_total"].corr(df["growth_inhibition"])
    results["corr_MIC_vs_growth"] = corr

    # 2. slopes for MIC vs cycle
    results["slope_chloro"] = compute_mic_slope(df, "MIC_chloro")
    results["slope_polyB"] = compute_mic_slope(df, "MIC_polyB")

    # 3. mean copper concentration (should alter MIC dynamics)
    results["mean_copper"] = df["copper"].mean()

    return results

# -----------------------------------------------------------
# Main QC evaluation
# -----------------------------------------------------------
def main():

    qc_records = []

    print("\nRunning biological QC diagnostics...\n")

    for agent, file_path in AGENT_FILES.items():
        df = pd.read_csv(file_path)

        # average across episodes
        summary = df.groupby("cycle").mean(numeric_only=True).reset_index()

        # compute biological signature metrics
        metrics = biological_signatures(summary)
        metrics["agent"] = agent

        qc_records.append(metrics)

        print(f"Agent: {agent}")
        print(f"  MIC–growth correlation: {metrics['corr_MIC_vs_growth']:.3f}")
        print(f"  MIC chloro slope:       {metrics['slope_chloro']:.3f}")
        print(f"  MIC polyB slope:        {metrics['slope_polyB']:.3f}")
        print(f"  Mean copper:            {metrics['mean_copper']:.1f}\n")

    qc_df = pd.DataFrame(qc_records)
    qc_df.to_csv(QC_DIR / "biological_qc_summary.csv", index=False)

    print(f"Biological QC results saved to {QC_DIR.resolve()}\n")
# -----------------------------------------------------------
if __name__ == "__main__":
    main()
# -----------------------------------------------------------
