---
title: "CMS Medicare Data: SQL Query Examples"
author: "Your Name"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 2
    number_sections: true
  pdf_document:
    toc: true
    number_sections: true
---

```{r setup, include=FALSE}
library(DBI)
library(RSQLite)
library(tidyverse)
library(googlesheets4)
# Load synthetic CMS data
cms_gs <- read_sheet("https://docs.google.com/spreadsheets/d/18JDU4ghGCpRgUSDmrjV3LGqaU2HwGiJuejS-8kAZg0Q/edit?usp=sharing")

# Load state code key
state_codes <- read_sheet("https://docs.google.com/spreadsheets/d/1lFTd1IgvkfYOVZGN-X-Mh_WTT0-9ewJPRe6uBDRM7ng/edit?usp=sharing")

# Simulate dummy education levels
set.seed(123)
cms_gs <- cms_gs %>%
  mutate(
    EDUCATION_LEVEL = sample(1:3, size = n(), replace = TRUE),
    BENE_RACE_CD = recode(BENE_RACE_CD,
                          `1` = "WHITE",
                          `2` = "BLACK",
                          `3` = "OTHERS",
                          `5` = "HISPANIC"),
    BENE_SEX_IDENT_CD = recode(BENE_SEX_IDENT_CD,
                               `1` = "MALE",
                               `2` = "FEMALE")
  )

# Merge with state code labels
cms_df <- cms_gs %>%
  left_join(state_codes, by = "SP_STATE_CODE")
# Create and connect to SQLite DB
con_cms <- dbConnect(SQLite(), dbname = "cms_sql.sqlite")

# Copy dataframe into database
copy_to(con_cms, cms_df, name = "cms_df", overwrite = TRUE)
SELECT 
  BENE_SEX_IDENT_CD AS sex,
  BENE_RACE_CD AS race,
  COUNT(DESYNPUF_ID) AS num_patients
FROM cms_df
WHERE SP_DIABETES = 1
GROUP BY sex, race
ORDER BY num_patients DESC;

SELECT 
  state_code,
  COUNT(DESYNPUF_ID) AS num_patients
FROM cms_df
WHERE SP_DEPRESSN = 1
GROUP BY state_code
ORDER BY num_patients DESC;

SELECT 
  ROUND(AVG(PPPYMT_IP), 2) AS avg_inpatient_reimb,
  ROUND(AVG(MEDREIMB_OP), 2) AS avg_outpatient_reimb,
  ROUND(AVG(EDUCATION_LEVEL), 2) AS avg_education_level
FROM cms_df
WHERE SP_CNCR = 1;

# Close DB connection
dbDisconnect(con_cms)
